### PR TITLE
Add 'SlaveThreadCrashed' exception type

### PR DESCRIPTION
**Pull request by mitchellwrosen**
This patch adds a `SlaveThreadCrashed` type, which is used to wrap exceptions thrown by slave threads before propagating them to the master.

It is similar to [ExceptionInLinkedThread](https://hackage.haskell.org/package/async-2.2.1/docs/Control-Concurrent-Async.html#t:ExceptionInLinkedThread) from `async`, and the purpose is the same: to distinguish asynchronous exceptions from synchronous ones.

### CODE REVIEW

**Comment by mitchellwrosen** [comment]
@nikita-volkov, interested in this one? I can fix up the patch if so.

**Comment by mitchellwrosen** [comment]
Hi @nikita-volkov, sorry to bother but can you take a look at this one when you get a chance? I believe it's an important change to make, otherwise `bracket`ing code may mistakenly believe its body has thrown a synchronous exception, when in fact a child thread died due to one.

**Comment by nikita-volkov** [comment]
Hi! Yes. This looks reasonable. Can you please synchronise this with the changes in "master"?

**Comment by mitchellwrosen** [comment]
Thanks, will do, first chance I get

**Comment by mitchellwrosen** [comment]
Thanks, will do, first chance I get

**Comment by mitchellwrosen** [comment]
Thanks, will do, first chance I get

**Comment by mitchellwrosen** [comment]
Thanks, will do, first chance I get

**Comment by mitchellwrosen** [comment]
Thanks, will do, first chance I get

**Comment by mitchellwrosen** [comment]
Thanks, will do, first chance I get

**Comment by mitchellwrosen** [comment]
Finally got around to this. :)

**Comment by nikita-volkov** [comment]
Thanks. Released

**Pull request merged**
